---
- name: Download and install additional libraries for Ubuntu 24
  tasks:
    - name: Download libtinfo5
      ansible.builtin.get_url:
        url: https://mirrors.edge.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo5_6.1-1ubuntu1_amd64.deb
        dest: /tmp/libtinfo5_6.1-1ubuntu1_amd64.deb

    - name: Download libncurses5
      ansible.builtin.get_url:
        url: https://mirrors.edge.kernel.org/ubuntu/pool/main/n/ncurses/libncurses5_6.1-1ubuntu1_amd64.deb
        dest: /tmp/libncurses5_6.1-1ubuntu1_amd64.deb

    - name: Install libtinfo5
      ansible.builtin.command:
        cmd: dpkg -i /tmp/libtinfo5_6.1-1ubuntu1_amd64.deb
      become: true

    - name: Install libncurses5
      ansible.builtin.command:
        cmd: dpkg -i /tmp/libncurses5_6.1-1ubuntu1_amd64.deb
      become: true
